# Generated by Django 2.1.1 on 2018-10-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userlogger',
            table='cdg_user_logger',
        ),
    ]
