# Generated by Django 2.1.1 on 2018-10-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20181004_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportDriver',
            fields=[
                ('supported_driver_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('driver_official_pip_name', models.CharField(max_length=200)),
                ('driver_description', models.TextField()),
                ('driver_version', models.CharField(max_length=50)),
                ('driver_for_source_system_name', models.CharField(max_length=100)),
                ('driver_icon_path', models.FilePathField()),
                ('driver_for_source_type', models.CharField(max_length=50)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(null=True)),
                ('created_by', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cdg_supported_drivers',
                'managed': True,
            },
        ),
    ]
