# Generated by Django 2.1.1 on 2018-10-04 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_supportdriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstalledDriver',
            fields=[
                ('installed_drivers_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('installed_drivers_name', models.CharField(max_length=100)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(null=True)),
                ('created_by', models.DateField(auto_now_add=True)),
                ('supported_driver_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.SupportDriver')),
            ],
        ),
    ]
