# Generated by Django 2.1.1 on 2018-10-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_installeddriver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installeddriver',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='installeddriver',
            table='cdg_installed_drivers',
        ),
    ]
