# Generated by Django 2.1.1 on 2018-10-04 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20181004_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStore',
            fields=[
                ('datastore_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('datastore_name', models.CharField(max_length=100)),
                ('datastore_host', models.CharField(max_length=50)),
                ('datastore_port', models.CharField(max_length=50)),
                ('datastore_directory', models.CharField(max_length=100)),
                ('datastore_connection_type', models.CharField(max_length=50)),
                ('ec_connection_success_flag', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(null=True)),
                ('created_by', models.DateField(auto_now_add=True)),
                ('datastore_installed_drivers_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.InstalledDriver')),
            ],
            options={
                'db_table': 'cdg_datastore',
                'managed': True,
            },
        ),
    ]
