# Generated by Django 2.1.1 on 2018-10-05 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_datastore'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishedConnections',
            fields=[
                ('established_connections_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('ec_name', models.CharField(max_length=100)),
                ('ec_userid', models.CharField(max_length=100)),
                ('ec_password', models.CharField(max_length=200)),
                ('ec_host', models.CharField(max_length=50)),
                ('ec_port', models.CharField(max_length=50)),
                ('ec_connectstring', models.CharField(max_length=200)),
                ('ec_connection_type', models.CharField(max_length=50)),
                ('ec_connection_success_flag', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(null=True)),
                ('created_by', models.DateField(auto_now_add=True)),
                ('ec_datastore_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.DataStore')),
                ('ec_installed_drivers_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.InstalledDriver')),
            ],
            options={
                'db_table': 'cdg_established_connections',
                'managed': True,
            },
        ),
    ]
