# Generated by Django 2.1.1 on 2018-10-05 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_establishedconnections'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablishedSource',
            fields=[
                ('established_sources_seq', models.IntegerField(primary_key=True, serialize=False)),
                ('es_name', models.CharField(max_length=50)),
                ('es_source_type', models.CharField(max_length=50)),
                ('es_schema', models.CharField(max_length=100)),
                ('es_directory', models.CharField(max_length=200)),
                ('es_connect_string', models.CharField(max_length=100)),
                ('es_is_active', models.BooleanField(default=False)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(null=True)),
                ('created_by', models.DateField(auto_now_add=True)),
                ('es_established_connections_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.EstablishedConnections')),
            ],
            options={
                'db_table': 'cdg_established_sources',
                'managed': True,
            },
        ),
    ]
